### PR TITLE
fix(replica_init): have genesis node init replica

### PR DESCRIPTION
**Pull request by oetyng**

### CODE REVIEW

**Review by joshuef — APPROVED** [review]

**Review by Yoga07 — DISMISSED** [review]

**Review by joshuef — DISMISSED** [review]
Currently cannot bootstrap a client against this node

**Comment by oetyng** [comment]
> Currently cannot bootstrap a client against this node

Why is that?

**Comment by joshuef** [comment]
```TRACE 2020-09-23T10:54:22Z [src/connection_manager.rs:278] Sending handshake request to bootstrapped node...
Error: QuicP2P error: Read exact error: stream finished early - CoreError::QuicP2p -> ReadExactError(FinishedEarly)```

**Comment by oetyng** [comment]
> ```
> Error: QuicP2P error: Read exact error: stream finished early - CoreError::QuicP2p -> ReadExactError(FinishedEarly)```
> ```

At what point is this, after promotion to Elder?

No trace of some panic?

Seems only a panic at line 126+ in replica_manager.rs could be responsible in this change?

**Comment by oetyng** [comment]
> Currently cannot bootstrap a client against this node

Fixed by this: https://github.com/maidsafe/sn_node/pull/1117/commits/657d832d0c3693adeac55db76464f8dc5eaed8fb

**Review by Yoga07 — DISMISSED** [review]

**Review by Yoga07 — DISMISSED** [review]

**Comment by oetyng** [comment]
Superseded by #1120.

**Pull request closed without merging**
